typecho/typecho

- var/Widget/Menu.php
> 删除乱入的<dt>标签

- var/Typecho/Request.php
修改了 /var/Typecho/Request.php:222 行。
> 修复检测不到 $_server['SERVER_PORT'] 导致无法访问后台的问题。

- admin/profile.php
- var/Widget/Users/Profile.php
| Before | After |
| --------- | ------ |
| ![qq20160211-0 2x](https://cloud.githubusercontent.com/assets/2725379/12979900/d4a56044-d114-11e5-937d-3466cdb1bb7c.png) | ![qq20160211-1 2x](https://cloud.githubusercontent.com/assets/2725379/12979906/dc173e6a-d114-11e5-9329-d8fc9975b80a.png) |
:laughing:
> 修正个人设置中插件接口错位的问题

- install.php
网上查了查w3school，发现标准的用例使用的是selected="selected"，而在js代码中使用selected=true来更改状态，具体可见下列网址：
1.在html标签中使用selected="selected"
http://www.w3school.com.cn/tags/att_option_selected.asp
2.在js中使用selected=true
http://www.w3school.com.cn/jsref/prop_option_selected.asp
> 我的IDE在selected=true这个地方提示我"没有定义的属性值"

- var/Helper.php
> 将cancle改成cancel

- var/Typecho/Db/Adapter/Mysqli.php
> Added support for MySQLi

- admin/css/style.css
- admin/scss/style.scss
> 修复后台数字序号样式自动换行

- admin/write-js.php
> Fix "insertTo is not a function"

- usr/themes/default/header.php
https://validator.w3.org/ 报错，上面一行的label没找到对应元素。
> for属性只对应id，给input补上id属性

- admin/backup.php
- var/Widget/Options/Discussion.php
Added gettext for a few strings in:
+ `typecho/admin/backup.php` (上传 and 从服务器)
+ `typecho/var/Widget/Options/Discussion.php` (avatar rating dropdown)
> added gettext in a few strings in backup.php and Discussion.php

- var/Typecho/Widget/Helper/Form/Element/Fake.php
开发插件的时候使用fake一直报错，后来发现初始化表单一栏有误
> fix Undefined variable: options in Fake.php

- var/Widget/Upload.php
- var/Widget/XmlRpc.php
> Support Windows Live Writer and Open Live Writer.

- var/Widget/Service.php
无法获取trackback url 地址 
https://github.com/typecho/typecho/issues/1082
> fix get trackback param bug

- var/Typecho/I18n/GetTextMulti.php
> fix #1118;

- admin/copyright.php
> Fix broken extends.typecho.org link

- admin/login.php
- admin/manage-comments.php
- admin/manage-medias.php
- admin/manage-pages.php
- admin/manage-users.php
- admin/write-page.php
- admin/write-post.php
- var/Typecho/Response.php
- var/Widget/Archive.php
- var/Widget/User.php
```
PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in typecho/var/Widget/Archive.php on line 1292
```
> Fix compatibility with PHP 8.1

- var/Widget/Ajax.php
fix #1354
---
旧版本没有提示的可以把这个删除再刷新
> Fix checkVersion

- var/Widget/Backup.php
> Fix pgsql reset id error

- admin/welcome.php
> Update admin welcome tip

- admin/footer.php
> Add admin/footer.php begin plugin

- var/Widget/Themes/Edit.php
> Fix missing change themeUrl

- admin/css/style.css
- var/Widget/Base/Contents.php
- var/Widget/Themes/Rows.php
- 修正 Windows 和 Linux 代码块没有中文备用字体，导致中文字体显示效果差的问题；
- 缩略图支持 avif 新时代图片格式
> Minor update

- var/Typecho/Widget/Helper/Form.php
> Fix the error of getting request parameters

- install.php
Fix https://github.com/typecho/typecho/pull/1357#issuecomment-1164353693
> Fix use SQLite error of windows install

- admin/css/style.css
- admin/src/scss/style.scss
> Adjust style of edit comments

- var/Widget/Archive.php
> Fix comments feed jump error

- admin/copyright.php
- admin/custom-fields.php
- admin/login.php
- admin/register.php
- install.php
- usr/themes/default/footer.php
- usr/themes/default/sidebar.php
- var/Utils/Upgrade.php
- var/Widget/Options/Discussion.php
- var/Widget/Options/Reading.php
- var/Widget/Users/Edit.php
- var/Widget/Users/Profile.php
`find ./* -name '*.php' | xargs sed -i 's|href="http://|href="https://|g'`
> Use https links

- var/Typecho/Validate.php
> Fix an XSS vulnerability in v1.2.1-rc

- var/Typecho/Http/Client.php
- var/Widget/Ajax.php
> Fixed ajax prompt message

- install.php
- install/Mysql.php
- install/Pgsql.php
- var/Typecho/Db/Adapter/Pdo/Pgsql.php
- var/Typecho/Db/Adapter/Pgsql.php
This feature will be verified in the dev branch.
> add pgsql ssl mode support (ref #1600)

- admin/login.php
> 增加邮箱也可以登陆的提示

- install.php
Added `_t()` to make able to translate the default comment during installation
> gettext for installation comment

- var/Widget/Options.php
> Fix installation failure

- usr/themes/default/style.css
> fix style error for code

- var/Typecho/Widget.php
> fix: choose the correct key when setting widget value

- var/IXR/Error.php
- var/IXR/Message.php
- var/IXR/Value.php
> fix: xmlrpc message args

- admin/write-js.php
> fix: remove special chars

- var/IXR/Message.php
- var/Widget/Options.php
fix #1648
Ref: <https://github.com/padraic/phpsecurity/blob/master/book/lang/en/source/_includes/XML-Injection.rst>
> fix: remove unnecessary DOCTYPE tags

- var/Typecho/Widget/Helper/PageNavigator.php
- var/Widget/Base/Comments.php
- var/Widget/Comments/Admin.php
- var/Widget/Comments/Archive.php
- var/Widget/Feedback.php
> Remove comment link if status is not approved

- var/Widget/Archive.php
> Fix assign null to property Widget\Archive::$archiveKeywords

- var/Widget/Base/Contents.php
> Fix missing get date

- var/Typecho/Common.php
> Fix missing WidgetException error message

- var/Typecho/Feed.php
> Fix TypeError: Typed property Typecho\Feed::$subTitle must be string

- var/Widget/Service.php
> Fix sendPingHandle warning

- var/Widget/Comments/Admin.php
> Fix manage comments failed

- var/Widget/Feedback.php
> fix typo "稍侯" to "稍候"

- var/Widget/Archive.php
> Remove debug output from category selection in Archive widget

- var/Widget/Register.php
> Fix missing nameExists and mailExists
