typecho/typecho

- install/Mysql.php
- var/Typecho/Common.php
使用[SAE本地环境](http://sae.sina.com.cn/doc/download.html)时遇到下面两个问题：
* 安装时提示如下的错误，注意错误信息为空字符串，并没有其他任何有用信息：
> 安装程序捕捉到以下错误:"". 程序被终止, 请检查您的配置信息.
原因是SAE本地环境下，虽然像`SAE_MYSQL_DB`这样的常量是定义了的，但并没有正确赋值，默认情况下`SAE_MYSQL_USER`和`SAE_MYSQL_PASS`都为空，导致安装时报错。
* 后台添加分类或启用插件或其他一些和Common.php中`slugName`函数相关的操作都会出现错误：
> Fatal error: Call to undefined function mb_regex_encoding() in typecho\var\Typecho\Common.php on line 810
原因是`mb_regex_encoding`函数在某些Windows下的PHP环境中没有定义，但是`mb_get_info`函数是定义了的。
> 修复两个在SAE本地环境出现的bug

- var/Json.php
虽然我都改成了 `Json` 但是我觉得用 `$this` 应该会更方便一点，而且事实上 http://mike.teczno.com/JSON/JSON.phps 源库文件好像也就是这么用的。
> Json.php 中的引用错误

- var/Typecho/Router.php
- var/Typecho/Router/Parser.php
- var/Typecho/Widget.php
更新一下 PHPDoc，主要改变了以下属性：
- @param
+ 修改 [Type] 参数错误。
+ 删除函数参数中不包含的。
- @return
+ 修改 [Type] 参数错误。
+ 删除构造函数的`@return`。 [constructors, the @return tag MAY be omitted here, in which case @return self is implied.](http://www.phpdoc.org/docs/latest/references/phpdoc/tags/return.html)
+ @var 根据下面的代码填了类型，修改了之前错误的写法。
+ @throws 两个函数都可能抛出`Exception`，都改成这个了。
刚开始看代码，慢慢看，顺便把 phpDoc 都改正确。
> update PHPDoc comments

- var/Typecho/Request.php
> 修复 iconv 函数参数传递错误

- usr/themes/default/header.php
Google Chrome Frame已于2014年2月25日正式停止维护与更新 https://zh.wikipedia.org/wiki/Google_Chrome_Frame
> 删除 Chrome Frame 的支持

- var/Widget/Archive.php
发布文章时，去掉"高级选项"->"权限控制"->"允许在聚合中出现", 却依然能在rss中看见。后来发现可能时那个判断的问题
> 修复聚合调用时的判断问题

- var/Typecho/Db/Adapter/Mysqli.php
现有的写错了，这个函数里面没有 resource 变量。
参见 http://php.net/manual/zh/mysqli.real-escape-string.php
> fix: Mysqli quoteColumn 函数参数调用错误

- usr/themes/default/archive.php
- usr/themes/default/index.php
- usr/themes/default/page.php
- usr/themes/default/post.php
小写的url只能用在itemprop上，例子见<https://schema.org/url>。
itemtype必须是绝对URL，类型名应该大写开头，见<https://schema.org/URL>。而且带itemtype的元素上必须有itemscope。
> url是BlogPosting的属性

- admin/header.php
`chrome=1`已不再使用。详见<https://stackoverflow.com/questions/22059060/is-it-still-valid-to-use-ie-edge-chrome-1>。
> Fix X-UA-Compatible

- var/Widget/Themes/List.php
修复主题根目录存在screenshot.png和其他图片时，主题展示图抓取其他图片的问题
> 主题缩略图使用screenshot命名的图片

- admin/css/style.css
编辑器预览界面，代码太长而没有换行会戳出屏幕外，故修复下，让其自动换行
> 修正编辑器预览界面代码不自动换行问题

- var/Widget/Options/Permalink.php
```
'/[year:digital:4]/[month:digital:2]/[day:digital:2]/[slug].html'
```
should match
```
/{year}/{month}/{day}/{slug}.html
```
instead of
```
/archives/{year}/{month}/{day}/{slug}.html
```
> chore: fix wrong slug prompt

- var/Typecho/Validate.php
fix: add support in email address (just like example+typecho@gmail.com)
Linked: #779
> fix: Support plus in email address

- admin/menu.php
解决插件注入右上角导航会有两个| | 出现。
例如：插件名| |用户名|登出|网站 此种现象出现，原因为换行空格导致的。
> 解决插件注入右上角导航会有两个 | | 出现

- var/Typecho/Request.php
当使用cdn或反向代理时，前后段协议不一致时，baseurl截取错误，会出现两种协议的url。
> fix error when use different protocol between reverse proxy and backend.

- tools/Dockerfile
- var/Widget/XmlRpc.php
**位于**```typecho/var/Widget/XmlRpc.php```
488.489行  **若不修改则导致无法编辑独立页面**
```php
$content['type'] = 'page';
$this->mwEditPost($blogId, $pageId, $userName, $password, $content, $publish);
```
其改为
```php
$content['post_type'] = 'page';
$this->mwEditPost($pageId, $userName, $password, $content, $publish);
```
1056行 **如不修改则导致无法获取垃圾评论和待审核评论**
```php 
$input['status'] = 'hold' == $input['status'] ? $input['status'] : $this->wordpressToTypechoStatus($struct['status']); 
``` 
**其改为** 
```php 
$input['status'] = $this->wordpressToTypechoStatus($struct['status'], 'comment');
```
1608行 **如不修改则导致无法判断该文章是否有草稿**
```php 
$this->typechoToWordpressStatus($posts->status, 'post')
``` 
**其改为** 
```php
$this->typechoToWordpressStatus(($posts->hasSaved || 'post_draft' == $posts->type) ? 'draft' : $posts->status, …
```
> 修复 XmlRpc 接口的几个错误问题

- var/Widget/Contents/Page/Edit.php
- var/Widget/Contents/Post/Edit.php
接口中返回的 cid 是根据 highlight id 获取的，但新建草稿时未设置该值。
> 修复通过 metaWeblog 接口新建草稿时返回 cid 错误的问题

- install.php
修复宝塔面板的网站目录带.导致sqlite路径校验不通过的问题
> 修复Sqlite目录带.校验不通过问题

- admin/write-js.php
Add 'allow-same-origin' into sandbox's attrs to fix that the article preview page does not match the real page.
给预览时的sandbox添加"allow-same-origin"，来避免跨域导致资源加载失效问题
> fix CORS issues in preview page. 修复文章预览页面跨域问题

- admin/common-js.php
- var/Typecho/Cookie.php
#1399 引入
设置了domain，js中没有设置，导致无法清空，notice会一直提醒
fix https://github.com/typecho/Dockerfile/issues/18
> Fix notice not clear

- admin/manage-posts.php
- admin/manage-users.php
bug描述：当管理员在文章管理页面，点击所有查看所有文章后，再通过这个页面进入作者文章管理页面时，仍会显示所有文章而不是当前作者的文章
> 修复管理员进入其他用户文章列表时显示所有文章的bug

- var/Typecho/Request.php
**修正 QUIC 协议访问 CDN 可能会出现的混合内容错误**
**使用 QUIC 协议访问 CDN，判断为 https**
---
部分支持 QUIC 协议访问的 CDN 回源携带的 ``HTTP_X_FORWARDED_PROTO`` 是 ``quic``，如果未能正确识别 QUIC 协议访问，则可能会导致请求出现混合内容错误
> Fix QUIC/https Mixed Content

- var/Typecho/Widget/Helper/Form.php
- var/Widget/XmlRpc.php
原因是在insertCategory时validate被goBack了，获取到的$formData是空的
Fix #1440
Fix #1340
> Fix category creation error when using xmlrpc

- var/Widget/Base/Comments.php
- var/Widget/Options/General.php
- 后台上传设置增加 avif 类型
- 后台 Avatar 头像支持原生懒加载
> Minor update

- admin/manage-comments.php
- admin/media.php
- admin/table-js.php
`.html()` can introudce cross-site-scripting (XSS) vulnerabilities with strings from untrusted sources. Use `.text()` instead or sanitize the input.
> Fix unsafe use of jQuery .html()

- install.php
- install/Mysql.php
- var/Typecho/Db/Adapter/Mysqli.php
- var/Typecho/Db/Adapter/Pdo/Mysql.php
支持了一下简版的ssl，测试planetscale通过。
腾讯云的云db，开启ssl以后连接使用证书，需要关闭验证，那开启ssl意义好像就没了 😅
```
Peer certificate CN=`TencentDB ROOT SERVER-CA' did not match expected CN...
```
Close #1508
> Support ssl for pdo_mysql and mysqli

- admin/custom-fields-js.php
- admin/custom-fields.php
这条 PR 修复了 #1597 问题，其问题的核心是在 Contents.php 当中的这段 Code:
```php
if (!$this->checkFieldName($name)) {
continue;
}
```
它检查了 field 名称的「有效性」，并且会自动过滤无效的field，无效 field 的标准是：
```php
public function checkFieldName(string $name): bool
{
return preg_match("/^[_a-z][_a-z0-9]*$/i", $name);
}
```
但是这一标准并没有在前端进行检验，提交的时候如果不满足条件过滤过程是静默的，这会让用于产生自己的数据没有被正确保存的幻觉。
本 PR 加入了一个实时的 field name 校验，如果输入了非法值，浏览器会立刻提醒用户进行修改。
> fix: Fix #1597

- var/Widget/Base/Metas.php
Fix #1672 
问题的发生过程：
- `Metas` 这里不知道为什么没有处理好 `getRouterParam()` 的默认情况。
- `Router` 在 `getRouterParam()` 时无法根据 `$route['params']` 生成正确的 `{page}` 模板参数。
- `Box` 中会对 `{page}` 模板参数进行字符串替换：`str_replace($this->pageHolder, $i, $this->pageTemplate)` 从而得到包含分页后缀的链接，但由于上面的过程不正确，这里得到的链接就缺失了分页后缀。
顺便排查了所有的 `ParamsDelegateInterface` ，大家在 `getRouterParam()` 的时候，default 情况都会将 `$key` 组合为 `{$key}` 成为模板参数，不知道为什么唯独 `Metas` 这里漏掉了。
Test：
观察生成的链接，确认分页后缀存在，且点击按钮能正常跳转分页。
> 修复“在查看某一分类或标签时无法正确生成分页链接”

- admin/editor-js.php
- var/Typecho/Common.php
- var/Widget/Base/Contents.php
- var/Widget/Contents/EditTrait.php
> Optimize applySlug

- var/Widget/Archive.php
Fix #1686 
打了一下 stacktrace ：
```
Typed property Widget\Archive::$countSql must not be accessed before initialization
Error: Typed property Widget\Archive::$countSql must not be accessed before initialization in <hide>/var/Widget/Archive.php:437
Stack trace:
#0 <hide>/var/Widget/Archive.php(712): Widget\Archive->getTotal()
#1 <hide>/usr/themes/default/index.php(39): Widget\Archive->pageNav()
#2 <hide>/var/Widget/Archive.php(1345): require_once('...')
#3 <hide>/admin/preview.php(19): Widget\Archive->render()
#4 {main}
```
追踪下去发现 `Archive.php(1345)` 这里引错了文件：
```
/** 输出模板 */
require_once $this->themeDir . $this->themeFile;
```
在预览时，本来这里应该根据文章类别，去引主题中的 `page.php` / `post.php` ，但这里却引用了 `index.php` ，造成了后续的错乱。
继续追踪，发现其根据 `archiveType` 决定引用的对象，但这里的 `archiveType` 的值却是 `revision` ，主题里没有 …
> Fix unable to preview revisions

- var/Widget/Contents/Attachment/Admin.php
> Fix unable to show attachment parent in manage-medias

- var/Typecho/Request.php
PHP 作为 CGI 脚本运行时，若接收到非空 body 的请求，根据 [RFC 3875 - The Common Gateway Interface (CGI) Version 1.1](https://datatracker.ietf.org/doc/rfc3875/)，会有以下行为：
1. HTTP header 中的 `Content-Type` 和 `Content-Length` header 会被赋值到 `$_SERVER['CONTENT_TYPE']` 以及 `$_SERVER['CONTENT_LENGTH']`
2. 同时 `$_SERVER['HTTP_CONTENT_TYPE']` 和 `$_SERVER['HTTP_CONTENT_LENGTH']` 不一定被赋值（对接不同的 sapi，比如 apache 或者 nginx，可能会有不同的行为）
- `Typecho\Request::getInstance()->getHeader('Content-Type')` 可能获取不到 `Content-Type` header
- <del>`Typecho\Request::getInstance()->isJson()` 可能返回不正确的值（由于获取不到 `Content-Type` header）</del>
- <del>`Typecho\Request::getInstance()->get('@json')` 可能错误地返回一个空值（由于 `isJson` 判断问题）</del>
因此，`Typecho\Request->getHeader` 函数需要对这两个 header 做额外处理，以解决上述问题。
使用以下脚本进行复现
```php
<?php
function dump_server_value($key) {
if …
```
> fix: getHeader for Content-Type & Content-Length

- var/IXR/Date.php
- var/Widget/XmlRpc.php
```
'date_modified'          => new Date($this->options->timezone + $posts->modified),
'date_modified_gmt'      => new Date($posts->modified),
```
未修正之前在`IXR\Date`中使用的`date`计算日期是依赖服务器时区，WP中已后缀`_gmt`为格林威治时间，`date_modified_gmt`不再是格林威治时间。
并且本地时间`date_modified`、格林威治时间`date_modified_gmt`因为快了$timezone时区，所以两个时间永远不正确。
> Fix timezone error in XmlRpc

- var/Typecho/I18n/GetText.php
修复了 #1797 中提到的PHP 8.3下有翻译情况下因为`$header`是`null`的时候调用`preg_match`报`deprecated`的问题
> Fix: fix preg_match parameter#2 $subject is null deprecated issue
